banknotes50 = input('Enter number of 50 euro banknotes:')
euro50 = int(banknotes50)
banknotes20 = input('Enter number of 20 euro banknotes:')
euro20 = int(banknotes20)
banknotes10 = input('Enter number of 10 euro banknotes:')
euro10 = int(banknotes10)
banknotes5 = input('Enter number of 5 euro banknotes:')
euro5 = int(banknotes5)
coins2 = input('Enter number of 2 euro coins:')
euro2 = int(coins2)
coins1 = input('Enter number of 1 euro coins:')
euro1 = int(coins1)
sum = (euro50*50) + (euro20*20) + (euro10*10) + (euro5*5) + (euro2*2) + (euro1*1)                                                               
print('You have', sum ,'euros')  
